version: 0.2
            
phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - mv target/spring-boot-todo-rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.war spring-boot-todo-rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.war
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - spring-boot-todo-rest-api-h2-aws-codepipeline-0.0.1-SNAPSHOT.war